# Generated by Django 2.0.5 on 2018-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.TextField(default='', verbose_name='教师描述'),
        ),
    ]
