# Generated by Django 2.0.5 on 2018-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessgae',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=500, verbose_name='information')),
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
            ],
        ),
    ]
