# Generated by Django 2.0.5 on 2018-05-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessgae',
            options={'verbose_name': '用户信息'},
        ),
    ]
