# Generated by Django 2.0.5 on 2018-05-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180502_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessgae',
            table='user_message',
        ),
    ]
